//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Infostructure.SimpleList.DataAccess
{
    public partial class SimpleListEntities : ObjectContext
    {
        public const string ConnectionString = "name=SimpleListEntities";
        public const string ContainerName = "SimpleListEntities";
    
        #region Constructors
    
        public SimpleListEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public SimpleListEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public SimpleListEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<SimpleList> SimpleLists
        {
            get { return _simpleLists  ?? (_simpleLists = CreateObjectSet<SimpleList>("SimpleLists")); }
        }
        private ObjectSet<SimpleList> _simpleLists;
    
        public ObjectSet<SimpleListItem> SimpleListItems
        {
            get { return _simpleListItems  ?? (_simpleListItems = CreateObjectSet<SimpleListItem>("SimpleListItems")); }
        }
        private ObjectSet<SimpleListItem> _simpleListItems;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;

        #endregion
    }
}
