//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Infostructure.SimpleList.DataModel
{
    public partial class SimpleList
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> UserID
        {
            get { return _userID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_userID != value)
                    {
                        if (User != null && User.ID != value)
                        {
                            User = null;
                        }
                        _userID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _userID;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateAdded
        {
            get;
            set;
        }
    
        public virtual bool AllDone
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;
    
        public virtual ICollection<SimpleListItem> SimpleListItems
        {
            get
            {
                if (_simpleListItems == null)
                {
                    var newCollection = new FixupCollection<SimpleListItem>();
                    newCollection.CollectionChanged += FixupSimpleListItems;
                    _simpleListItems = newCollection;
                }
                return _simpleListItems;
            }
            set
            {
                if (!ReferenceEquals(_simpleListItems, value))
                {
                    var previousValue = _simpleListItems as FixupCollection<SimpleListItem>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSimpleListItems;
                    }
                    _simpleListItems = value;
                    var newValue = value as FixupCollection<SimpleListItem>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSimpleListItems;
                    }
                }
            }
        }
        private ICollection<SimpleListItem> _simpleListItems;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.SimpleLists.Contains(this))
            {
                previousValue.SimpleLists.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.SimpleLists.Contains(this))
                {
                    User.SimpleLists.Add(this);
                }
                if (UserID != User.ID)
                {
                    UserID = User.ID;
                }
            }
            else if (!_settingFK)
            {
                UserID = null;
            }
        }
    
        private void FixupSimpleListItems(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SimpleListItem item in e.NewItems)
                {
                    item.SimpleList = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SimpleListItem item in e.OldItems)
                {
                    if (ReferenceEquals(item.SimpleList, this))
                    {
                        item.SimpleList = null;
                    }
                }
            }
        }

        #endregion
    }
}
