//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Infostructure.SimpleList.DataModel
{
    public partial class User
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Password
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<SimpleList> SimpleLists
        {
            get
            {
                if (_simpleLists == null)
                {
                    var newCollection = new FixupCollection<SimpleList>();
                    newCollection.CollectionChanged += FixupSimpleLists;
                    _simpleLists = newCollection;
                }
                return _simpleLists;
            }
            set
            {
                if (!ReferenceEquals(_simpleLists, value))
                {
                    var previousValue = _simpleLists as FixupCollection<SimpleList>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSimpleLists;
                    }
                    _simpleLists = value;
                    var newValue = value as FixupCollection<SimpleList>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSimpleLists;
                    }
                }
            }
        }
        private ICollection<SimpleList> _simpleLists;

        #endregion
        #region Association Fixup
    
        private void FixupSimpleLists(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SimpleList item in e.NewItems)
                {
                    item.User = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SimpleList item in e.OldItems)
                {
                    if (ReferenceEquals(item.User, this))
                    {
                        item.User = null;
                    }
                }
            }
        }

        #endregion
    }
}
